### PR TITLE
Commit fix for issue #122 in oleksis/youtube-dl-gui

### PR DESCRIPTION
**Pull request by gitgeoff**
"Paste In URL Field Not Working" on Mac and Probably Linux
Fix logic for testing status of the clipboard, and implement fix for UNICODE per https://github.com/wxWidgets/Phoenix/issues/2042

### CODE REVIEW

**Comment by oleksis** [comment]
@gitgeoff Can test the new changes for macOS. If work as expected we can merge

**Comment by gitgeoff** [comment]
> @gitgeoff Can test the new changes for macOS. If work as expected we can merge

I have pulled your revision to my local copy but can't figure out how to test the local version on Mac. Do I go into youtube-dl-gui and run setup.sh? The build from source instructions in Readme.md feel disconnected from what I see locally.

**Comment by gitgeoff** [comment]
> > @gitgeoff Can test the new changes for macOS. If work as expected we can merge
> 
> @oleksis I have pulled your revision to my local copy but can't figure out how to test the local version on Mac. Do I go into youtube-dl-gui and run setup.sh? The build from source instructions in Readme.md feel disconnected from what I see locally.

Specifically, I tried following the Install from Source instructions. Ran through getting the venv setup, then running `make install` results in an error: 

```
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [8 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/private/var/folders/ny/yz2ldzhd68148kd6jhyvzf100000gn/T/pip-resolver-dxy3ppwt/wxpython/setup.py", line 27, in <module>
            from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
          File "/private/var/folders/ny/yz2ldzhd68148kd6jhyvzf100000gn/T/pip-resolver-dxy3ppwt/wxpython/buildtools/config.py", line 30, in <module>
            from attrdict import AttrDict
        ModuleNotFoundError: No module named 'attrdict'
        [end of output]
```

**Comment by gitgeoff** [comment]
> No module named 'attrdict'

Looks like the requirements.in method of including attrdict3 is not working. There is a comment in that file about a "fix" being added to include it. I tried running `pip3 install attrdict3` and then running `make install` again and the install ran past the original fail point, but then still failed later:

```
  ERROR: Failed building wheel for wxpython
  Running setup.py clean for wxpython
Failed to build wxpython
Installing collected packages: polib, altgraph, pypubsub, pyinstaller-hooks-contrib, pillow, numpy, macholib, attrdict, wxpython, pyinstaller
  Running setup.py install for wxpython ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for wxpython did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ny/yz2ldzhd68148kd6jhyvzf100000gn/T/pip-install-ri3v732f/wxpython_a9f00691641941f39c9630d6d588a2f8/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/ny/yz2ldzhd68148kd6jhyvzf100000gn/T/pip-install-ri3v732f/wxpython_a9f00691641941f39c9630d6d588a2f8/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
        File "/Users/username/Desktop/ydl_gui/youtube-dl-gui/venv/lib/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/Users/username/Desktop/ydl_gui/youtube-dl-gui/venv/lib/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

```

**Comment by oleksis** [comment]
When you active the virtual environment
```bash
source venv/bin/activate
```
After you need to install `wxPython` in the virtualenv before run `yt-dlg`

> Specifically, I tried following the Install from Source instructions. Ran through getting the venv setup, then running `make install` results in an error:
> 
> ```
> WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
>     error: subprocess-exited-with-error
>     
>     × python setup.py egg_info did not run successfully.
>     │ exit code: 1
>     ╰─> [8 lines of output]
>         Traceback (most recent call last):
>           File "<string>", line 2, in <module>
>           File "<pip-setuptools-caller>", line 34, in <module>
>           File "/private/var/folders/ny/yz2ldzhd68148kd6jhyvzf100000gn/T/pip-resolver-dxy3ppwt/wxpython/setup.py", line 27, in <module>
>             from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
>           File "/private/var/folders/ny/yz2ldzhd68148kd6jhyvzf100000gn/T/pip-resolver-dxy3ppwt/wxpython/buildtools/config.py", line 30, in <module>
>             from attrdict import AttrDict
>         ModuleNotFoundError: No module named 'attrdict'
>         [end of output]
> ```

This is [know issue](https://github.com/wxWidgets/Phoenix/issues/2296#issuecomment-1426606107) for the last version wxPython 4.2.0

Install the [requeriments](https://github.com/oleksis/youtube-dl-gui/blob/master/requirements/requirements.txt#L3)

`python3 -m pip install ./requirements/requirements.tx`

Make sure install the [requirements for compile wxPython](https://github.com/oleksis/youtube-dl-gui#custom-python-build-with---enable-framework) with the version of Python you are using on macOS.

- [How to use wxPython with virtualenv on Mac OSX](https://wiki.wxpython.org/wxPythonVirtualenvOnMac)

Then install `yt-dlg` from the clone repository

`python3 -m pip install -e .`

**Comment by gitgeoff** [comment]
> python3 -m pip install ./requirements/requirements.tx

Running `python -m pip install -r requirements/requirements.in` results in the same error.

**Comment by gitgeoff** [comment]
> > python3 -m pip install ./requirements/requirements.tx
> 
> Running `python -m pip install -r requirements/requirements.in` results in the same error.

That is running in the venv.

**Comment by oleksis** [comment]
> That is running in the venv.

Give a try to `pyenv`:
- Install Pyenv using [Homebrew](https://github.com/pyenv/pyenv#homebrew-in-macos)

**Comment by oleksis** [comment]
I trying Oracle VM VirtualBox 7 and macOS Ventura and for hours stay in this screen ⏱️
image

**Comment by oleksis** [comment]
@gitgeoff Thanks for the contribution. Tested in the VM: macOS Ventura, Python 3.10.10, wxPython 4.2 . Give a try!

**Pull request merged**
