### PR TITLE
Adding sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**
Hello!

Here you are a translations for sq locale.

TIA
Besnik

### CODE REVIEW

**Comment by oleksis** [comment]
> Here you are a translations for sq locale.

Can use this flag 🇦🇱 (Albania) for the icon in the languages?

**Comment by ujdhesa** [comment]
> > Here you are a translations for sq locale.
> 
> Can use this flag albania (Albania) for the icon in the languages?



> > Here you are a translations for sq locale.
> 
> Can use this flag albania (Albania) for the icon in the languages?

Yes, you can. That’s the one. :) Thank you!

**Comment by oleksis** [comment]
> Yes, you can. That’s the one. :) Thank you!

Thanks to you for the translation 🙏🏾

**Comment by oleksis** [comment]
@ujdhesa I share in Reddit: [Youtube-DLG 1.2.0](https://www.reddit.com/r/youtubedl/comments/mn231m/youtubedlg_120/?utm_source=share)

**Pull request merged**
